apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../baseBAR/data-api
  - ../../baseFOO/frontend
images:
  - name: data-api
    newName: kubewsbenc.azurecr.io/smilr/data-api
    newTag: stable
  - name: frontend
    newName: kubewsbenc.azurecr.io/smilr/frontend
    newTag: stable
