kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mongodb
  namespace: default

spec:
  template:
    spec:
      containers:
        - name: mongodb-container
          image: mongo:4.4.12-focal
